/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rationdistribution;

import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class CardHolder extends javax.swing.JFrame {

    /**
     * Creates new form CardHolder
     */
    public CardHolder() {
        initComponents();
        Connect();
        AutoId();
        AutoId1();
        CardHolder_Table();
    }
    Connection con;
    PreparedStatement pat;
    ResultSet rs;

    public void Connect() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(user11.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rationsystem", "root", "Sanju@0830");
        } catch (SQLException ex) {
            Logger.getLogger(user11.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    public void AutoId() {
    try {
        Statement s = con.createStatement();
        rs = s.executeQuery("SELECT MAX(CAST(SUBSTRING(Card_Number, 3) AS SIGNED)) FROM cardholder");
        rs.next();
        long id = rs.getLong(1);
        id++;
        jLabel9.setText("CD" + String.format("%03d", id));
    } catch (SQLException ex) {
        Logger.getLogger(CardHolder.class.getName()).log(Level.SEVERE, null, ex);
    }
}


    public void AutoId1() {
    try {
        Statement s = con.createStatement();
        rs = s.executeQuery("select MAX(Holder_Id) from cardholder");
        rs.next();
        String maxHolderId = rs.getString("MAX(Holder_Id)");
        if (maxHolderId == null || maxHolderId.isEmpty()) {
            jLabel10.setText("HID01");
        } else {
            // Extract the numeric part of the holder ID
            String numericPart = maxHolderId.substring(3);

            // Check if the remaining part is numeric
            try {
                int id = Integer.parseInt(numericPart) + 1;
                jLabel10.setText("HID" + String.format("%02d", id));
            } catch (NumberFormatException ex) {
                // Handle the case where the numeric part is not a valid integer
                // Set a default value or handle it as appropriate for your application
                jLabel10.setText("DefaultHolderId");
            }
        }
    } catch (SQLException ex) {
        Logger.getLogger(CardHolder.class.getName()).log(Level.SEVERE, null, ex);
    }
}


    public void CardHolder_Table() {
        try {
            pat = con.prepareStatement("select * from cardholder");
            rs = pat.executeQuery();
            ResultSetMetaData Rsm = rs.getMetaData();
            int c;
            c = Rsm.getColumnCount();
            DefaultTableModel df = (DefaultTableModel) jTable1.getModel();
            df.setRowCount(0);
            while (rs.next()) {
                Vector v2 = new Vector();

                for (int i = 1; i <= c; i++) {
                    v2.add(rs.getString("Card_Number"));
                    v2.add(rs.getString("Holder_Id"));

                    v2.add(rs.getString("Holder_Name"));
                    v2.add(rs.getString("Card_Type"));
                    v2.add(rs.getInt("Age"));
                    v2.add(rs.getString("Address"));
                    v2.add(rs.getInt("No_Fam_Mem"));
                    
                    
                }
                df.addRow(v2);

            }
        } catch (SQLException ex) {
            Logger.getLogger(RationShopDealer.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtHolderName = new javax.swing.JTextField();
        txtCardType = new javax.swing.JComboBox<>();
        txtAge = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtFamMem = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setText("Card Holder Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 250, 41));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 51));
        jLabel2.setText("Card Type");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 70, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 51));
        jLabel3.setText("Holder Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 120, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 51));
        jLabel4.setText("Holder Id");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 166, 80, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 51));
        jLabel5.setText("Card Number");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 117, 90, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 51));
        jLabel6.setText("Address");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 90, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 51));
        jLabel7.setText("Number of Family Members");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 190, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 51));
        jLabel8.setText("Age");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 40, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 51));
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 51));
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));
        getContentPane().add(txtHolderName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 170, -1));

        txtCardType.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCardType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "APL", "BPL", "AAY", "Annapurna" }));
        txtCardType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCardTypeActionPerformed(evt);
            }
        });
        getContentPane().add(txtCardType, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));
        getContentPane().add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 170, -1));
        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 170, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Card_Number", "Holder_Id", "Holder_Name", "Card_Type", "Age", "Address", "No. of Family Members"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 930, -1));
        getContentPane().add(txtFamMem, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 170, -1));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addd.png"))); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 130, 30));

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new product.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, 120, 30));

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-delete-24.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, 130, 30));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit small.png"))); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 530, 120, 30));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 0, 51));
        jLabel11.setText("View Of CardHolder Details");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, 220, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCardTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCardTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCardTypeActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:

         String Card_Number = jLabel9.getText();
    String Holder_Id = jLabel10.getText();
    String Holder_Name = txtHolderName.getText();
    String Card_Type = txtCardType.getSelectedItem().toString();
    
    // Initialize Age and No_Fam_Mem variables
    int Age = 0;
    int No_Fam_Mem = 0;

    // Parse Age and No_Fam_Mem fields as integers
    try {
        Age = Integer.parseInt(txtAge.getText());
        No_Fam_Mem = Integer.parseInt(txtFamMem.getText());
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Please enter valid numeric values for Age and Number of Family Members.", "Error", JOptionPane.ERROR_MESSAGE);
        return; // Exit the method to prevent further execution
    }

    String Address = txtAddress.getText();

    try {
        // Prepare the SQL statement
        pat = con.prepareStatement("insert into cardholder(Card_Number,Holder_Id,Holder_Name,Card_Type,Age,Address,No_Fam_Mem)values(?,?,?,?,?,?,?)");
        pat.setString(1, Card_Number);
        pat.setString(2, Holder_Id);
        pat.setString(3, Holder_Name);
        pat.setString(4, Card_Type);
        pat.setInt(5, Age);
        pat.setString(6, Address);
        pat.setInt(7, No_Fam_Mem);
        
        // Execute the SQL statement
        pat.executeUpdate();
        
        // Display success message to the user
        JOptionPane.showMessageDialog(this, "Card Holder details inserted successfully");
        
        // Reset input fields and update table
        AutoId();
        AutoId1();
        txtHolderName.setText("");
        txtCardType.setSelectedIndex(-1);
        txtAge.setText("");
        txtAddress.setText("");
        txtFamMem.setText("");
        txtHolderName.requestFocus();
        CardHolder_Table();

    } catch (SQLException ex) {
        // Handle SQL exception
        Logger.getLogger(CardHolder.class.getName()).log(Level.SEVERE, null, ex);
    }


    }//GEN-LAST:event_btnAddActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel d1 = (DefaultTableModel) jTable1.getModel();
        int SelectIndex = jTable1.getSelectedRow();
        jLabel9.setText(d1.getValueAt(SelectIndex, 0).toString());
        jLabel10.setText(d1.getValueAt(SelectIndex, 1).toString());
        txtHolderName.setText(d1.getValueAt(SelectIndex, 2).toString());
        txtCardType.setSelectedItem(d1.getValueAt(SelectIndex, 3).toString());

         txtAge.setText(d1.getValueAt(SelectIndex, 4).toString());
         txtAddress.setText(d1.getValueAt(SelectIndex, 5).toString());
         txtFamMem.setText(d1.getValueAt(SelectIndex, 6).toString());
         btnAdd.setEnabled(false);
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
    
    
    String Card_Number = jLabel9.getText();
    String Holder_Id = jLabel10.getText();
    String Holder_Name = txtHolderName.getText();
    String Card_Type = txtCardType.getSelectedItem().toString();
    
    // Initialize Age and No_Fam_Mem variables
    int Age = 0;
    int No_Fam_Mem = 0;

    // Parse Age and No_Fam_Mem fields as integers
    try {
        Age = Integer.parseInt(txtAge.getText());
        No_Fam_Mem = Integer.parseInt(txtFamMem.getText());
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Please enter valid numeric values for Age and Number of Family Members.", "Error", JOptionPane.ERROR_MESSAGE);
        return; // Exit the method to prevent further execution
    }

    String Address = txtAddress.getText();

    try {
        // Prepare the SQL statement
        pat = con.prepareStatement("update cardholder set Holder_Name=?,Card_Type=?,Age=?,Address=?,No_Fam_Mem=? where Card_Number=? and Holder_Id=?");
        
        pat.setString(1, Holder_Name);
        pat.setString(2, Card_Type);
        pat.setInt(3, Age);
        pat.setString(4, Address);
        pat.setInt(5, No_Fam_Mem);
        pat.setString(6, Card_Number);
        pat.setString(7, Holder_Id);
        
        // Execute the SQL statement
        pat.executeUpdate();
        
        // Display success message to the user
        JOptionPane.showMessageDialog(this, "Card Holder details updated successfully");
        
        // Reset input fields and update table
        AutoId();
        AutoId1();
        txtHolderName.setText("");
        txtCardType.setSelectedIndex(-1);
        txtAge.setText("");
        txtAddress.setText("");
        txtFamMem.setText("");
        txtHolderName.requestFocus();
        CardHolder_Table();
        btnAdd.setEnabled(true);

    } catch (SQLException ex) {
        // Handle SQL exception
        Logger.getLogger(CardHolder.class.getName()).log(Level.SEVERE, null, ex);
    }


    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
    String Card_Number = jLabel9.getText();
    String Holder_Id = jLabel10.getText();
    

    try {
        // Prepare the SQL statement
        pat = con.prepareStatement("Delete from cardholder where Card_Number=? and Holder_Id=?");
        
        
        pat.setString(1, Card_Number);
        pat.setString(2, Holder_Id);
        
        // Execute the SQL statement
        pat.executeUpdate();
        
        // Display success message to the user
        JOptionPane.showMessageDialog(this, "Card Holder details deleted successfully");
        
        // Reset input fields and update table
        AutoId();
        AutoId1();
        txtHolderName.setText("");
        txtCardType.setSelectedIndex(-1);
        txtAge.setText("");
        txtAddress.setText("");
        txtFamMem.setText("");
        txtHolderName.requestFocus();
        CardHolder_Table();
        btnAdd.setEnabled(true);

    } catch (SQLException ex) {
        // Handle SQL exception
        Logger.getLogger(CardHolder.class.getName()).log(Level.SEVERE, null, ex);
    }

    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CardHolder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CardHolder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CardHolder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CardHolder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CardHolder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JComboBox<String> txtCardType;
    private javax.swing.JTextField txtFamMem;
    private javax.swing.JTextField txtHolderName;
    // End of variables declaration//GEN-END:variables
}
