/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rationdistribution;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class Transportationn extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    public Transportationn() {
        initComponents();
        Connect();
        AutoId();
        transporttable();
    }
    Connection con;
    PreparedStatement pat;
    ResultSet rs;

    public void Connect() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(user11.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rationsystem", "root", "Sanju@0830");
        } catch (SQLException ex) {
            Logger.getLogger(user11.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    public void AutoId() {
        try {
            Statement s = con.createStatement();
            rs = s.executeQuery("select MAX(Shipment_Id) from transportt");
            rs.next();
            rs.getString("MAX(Shipment_Id)");
            if (rs.getString("MAX(Shipment_Id)") == null) {
                jLabel7.setText("SP001");

            } else {
                long id = Long.parseLong(rs.getString("MAX(Shipment_Id)").substring(2, rs.getString("MAX(Shipment_Id)").length()));
                id++;
                jLabel7.setText("SP" + String.format("%03d", id));
            }
        } catch (SQLException ex) {
            Logger.getLogger(rationitem.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    public void transporttable(){
        try {
            pat = con.prepareStatement("select * from transportt");
            rs = pat.executeQuery();

            ResultSetMetaData RSM = rs.getMetaData();
            int c;
            c = RSM.getColumnCount();
            DefaultTableModel df = (DefaultTableModel) jTable1.getModel();
            df.setRowCount(0);

            while (rs.next()) {
                Vector v2 = new Vector();
                for (int i = 1; i <= c; i++) { // Use the number of columns in the loop condition
                    v2.add(rs.getString("Shipment_Id"));
                    v2.add(rs.getString("source_location"));
                    v2.add(rs.getString("destination_location"));
                    v2.add(rs.getString("delivery_status"));
                    v2.add(rs.getString("Shop_Id"));
                }
                df.addRow(v2); // Move the addRow operation outside the loop
            }

        } catch (SQLException ex) {
            Logger.getLogger(Transportationn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtSource_Location = new javax.swing.JTextField();
        txtDelivery_Status = new javax.swing.JTextField();
        txtDestination_Location = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtShop_Id = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setText("Shipment_Id");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 90, -1));

        jLabel2.setBackground(new java.awt.Color(51, 0, 51));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 51));
        jLabel2.setText("Transportation Details");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 270, 60));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 51));
        jLabel4.setText("Source_Location");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 110, -1));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addd.png"))); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit small.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, -1, 30));

        btndelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-delete-24.png"))); // NOI18N
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, -1, -1));

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-edit-16.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 51));
        jLabel5.setText("Destination Location");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        jLabel6.setText(" ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 51));
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 60, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 51));
        jLabel8.setText("Delivery_Status");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Shipment_Id", "Source_location", "Destination_location", "Delivery_Status", "Shop_Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 610, -1));
        getContentPane().add(txtSource_Location, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 180, -1));
        getContentPane().add(txtDelivery_Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 180, -1));

        txtDestination_Location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDestination_LocationActionPerformed(evt);
            }
        });
        getContentPane().add(txtDestination_Location, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 180, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 51));
        jLabel3.setText("Shop_Id");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));
        getContentPane().add(txtShop_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 180, -1));

        jLabel10.setBackground(new java.awt.Color(51, 0, 51));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 51));
        jLabel10.setText("View of Transportation Details");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        
        
           String Shipment_Id = jLabel7.getText();
        
       

        try {
            // TODO add your handling code here:
            pat = con.prepareStatement("delete from transportt  where Shipment_Id=?");
            
           
            pat.setString(1, Shipment_Id);
            pat.executeUpdate();
            JOptionPane.showMessageDialog(this,"Transportation  details deleted successfully");
            AutoId();
            txtSource_Location.setText("");
            txtDestination_Location.setText("");
            txtDelivery_Status.setText("");
            txtShop_Id.setText("");
            
            txtSource_Location.requestFocus();
            transporttable();
            btnAdd.setEnabled(true);
            
            
            

        } catch (SQLException ex) {
            Logger.getLogger(Transportationn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String Shipment_Id = jLabel7.getText();
        String Source_Location = txtSource_Location.getText();
         String Destination_Location = txtDestination_Location.getText();
          String delivery_status = txtDelivery_Status.getText();
           String Shop_Id = txtShop_Id.getText();
        
       

        try {
            // TODO add your handling code here:
            pat = con.prepareStatement("insert into transportt(Shipment_Id,source_location,destination_location,delivery_status,Shop_Id)values(?,?,?,?,?)");
            pat.setString(1, Shipment_Id);
            pat.setString(2, Source_Location);
            pat.setString(3, Destination_Location);
            pat.setString(4, delivery_status);
            pat.setString(5, Shop_Id);
            pat.executeUpdate();
            JOptionPane.showMessageDialog(this,"Transportation  details inserted successfully");
            AutoId();
            txtSource_Location.setText("");
            txtDestination_Location.setText("");
            txtDelivery_Status.setText("");
            txtShop_Id.setText("");
            
            txtSource_Location.requestFocus();
            transporttable();
            
            

        } catch (SQLException ex) {
            Logger.getLogger(Transportationn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         DefaultTableModel d1 = (DefaultTableModel) jTable1.getModel();
        int SelectIndex = jTable1.getSelectedRow();
        jLabel7.setText(d1.getValueAt(SelectIndex, 0).toString());
        txtSource_Location.setText(d1.getValueAt(SelectIndex, 1).toString());
        txtDestination_Location.setText(d1.getValueAt(SelectIndex, 2).toString());
         txtDelivery_Status.setText(d1.getValueAt(SelectIndex, 3).toString());
         txtShop_Id.setText(d1.getValueAt(SelectIndex, 4).toString());
         
         btnAdd.setEnabled(false);
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        String Source_Location = txtSource_Location.getText();
         String Destination_Location = txtDestination_Location.getText();
          String delivery_status = txtDelivery_Status.getText();
           String Shop_Id = txtShop_Id.getText();
           String Shipment_Id = jLabel7.getText();
        
       

        try {
            // TODO add your handling code here:
            pat = con.prepareStatement("update transportt set source_location=? ,destination_location=?,delivery_status=?,Shop_Id=? where Shipment_Id=?");
            
            pat.setString(1, Source_Location);
            pat.setString(2, Destination_Location);
            pat.setString(3, delivery_status);
            pat.setString(4, Shop_Id);
            pat.setString(5, Shipment_Id);
            pat.executeUpdate();
            JOptionPane.showMessageDialog(this,"Transportation  details are updated successfully");
            AutoId();
            txtSource_Location.setText("");
            txtDestination_Location.setText("");
            txtDelivery_Status.setText("");
            txtShop_Id.setText("");
            
            txtSource_Location.requestFocus();
            transporttable();
            btnAdd.setEnabled(true);
            
            
            

        } catch (SQLException ex) {
            Logger.getLogger(Transportationn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtDestination_LocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDestination_LocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDestination_LocationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transportationn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transportationn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transportationn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transportationn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transportationn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btndelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDelivery_Status;
    private javax.swing.JTextField txtDestination_Location;
    private javax.swing.JTextField txtShop_Id;
    private javax.swing.JTextField txtSource_Location;
    // End of variables declaration//GEN-END:variables
}
